services:
  app:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
      args:
        USER: app
        UID: 1000
    container_name: laravel_app
    volumes:
      - ./app:/var/www
    working_dir: /var/www
    ports:
      - "8000:8000"  # Laravel
    depends_on:
      - db
    networks:
      - laravel

  node:
    image: node:20
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    ports:
      - "5173:5173"  # Puerto de Vite
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
