services:
  app:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
      args:
        USER: app
        UID: 1000
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    networks:
      - laravel

  node:
    image: node:20
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: sh     # <--- mantiene el contenedor "vivo"
    tty: true        # <--- ayuda a que sh no cierre por EOF
    ports:
      - "5173:5173"
    networks:
      - laravel
      


  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
